#!/usr/bin/env node
// Rewrites the skill catalog table in README.md from the skills themselves, so
// the list cannot drift from what is installed.
// Run with: node scripts/catalog.mjs        (rewrite)
//           node scripts/catalog.mjs --check (fail if stale, for CI)
import { readFileSync, writeFileSync, readdirSync, existsSync, statSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const README = join(ROOT, 'README.md');
const START = '<!-- catalog:start -->';
const END = '<!-- catalog:end -->';
const CHECK = process.argv.includes('--check');

function frontmatter(raw) {
  if (!raw.startsWith('---\n')) return {};
  const end = raw.indexOf('\n---', 3);
  if (end === -1) return {};
  const out = {};
  let key = null;
  for (const line of raw.slice(4, end + 1).split('\n')) {
    if (!line.trim()) continue;
    const top = /^([A-Za-z0-9_-]+):[ \t]*(.*)$/.exec(line);
    if (top && !/^[ \t]/.test(line)) {
      key = top[1];
      let v = top[2].trim();
      if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) {
        v = v.slice(1, -1);
      }
      out[key] = v;
    } else if (key && /^[ \t]/.test(line)) {
      out[key] = `${out[key]} ${line.trim()}`;
    }
  }
  return out;
}

// The catalog wants "what it does", not the trigger phrases that follow it.
function summarize(description) {
  if (!description) return '';
  const cut = description.search(/\s+Use (when|whenever|this|it|for|if)\b/i);
  const head = cut === -1 ? description : description.slice(0, cut);
  const firstSentence = /^(.+?\.)(\s|$)/s.exec(head.trim());
  const text = (firstSentence ? firstSentence[1] : head).trim().replace(/\|/g, '\\|');
  return text.length > 180 ? `${text.slice(0, 177).trimEnd()}...` : text;
}

const rows = [];
const pluginsDir = join(ROOT, 'plugins');
for (const plugin of readdirSync(pluginsDir).filter((d) => statSync(join(pluginsDir, d)).isDirectory())) {
  const skillsDir = join(pluginsDir, plugin, 'skills');
  if (!existsSync(skillsDir)) continue;
  for (const name of readdirSync(skillsDir).sort()) {
    const file = join(skillsDir, name, 'SKILL.md');
    if (!existsSync(file)) continue;
    const fm = frontmatter(readFileSync(file, 'utf8'));
    rows.push({
      name,
      plugin,
      summary: summarize(fm.description),
      path: `plugins/${plugin}/skills/${name}/SKILL.md`,
    });
  }
}

const table = [
  `| Command | What it does |`,
  `| :------ | :----------- |`,
  ...rows.map((r) => `| [\`/${r.name}\`](${r.path}) | ${r.summary} |`),
].join('\n');

const block = `${START}\n\n${table}\n\n${rows.length} skill${rows.length === 1 ? '' : 's'}. This table is generated by \`scripts/catalog.mjs\`; edit the skills, not the table.\n\n${END}`;

const readme = readFileSync(README, 'utf8');
const s = readme.indexOf(START);
const e = readme.indexOf(END);
if (s === -1 || e === -1) {
  console.error(`README.md is missing the ${START} / ${END} markers`);
  process.exit(1);
}
const updated = readme.slice(0, s) + block + readme.slice(e + END.length);

if (updated === readme) {
  console.log(`Catalog is up to date (${rows.length} skills).`);
  process.exit(0);
}
if (CHECK) {
  console.error('Catalog in README.md is stale. Run: node scripts/catalog.mjs');
  process.exit(1);
}
writeFileSync(README, updated);
console.log(`Catalog rewritten (${rows.length} skills).`);
